feat: Improve test coverage of crypto.py
RedHatInsights/insights-ansible-playbook-verifier pull request #24
Opened 2024-11-07 10:41 UTC by pkoprda

* Card ID: CCT-706

While existing tests catch basic invalid playbook scenarios, this update aims to create more tests that cover specific verification failure points. Adding new unit tests helps "freeze" expected verification behavior, making it easier to detect unintended changes in the future.

2024-11-07 12:59 UTC, m-horky requested changes
Looking good. I have some notes.

2024-11-07 15:10 UTC, pkoprda commented on python/tests-unit/test_crypto.py
> +        assert result is None
Yes, you are right that there was a bug in the GPG code. I had to change the condition in `evaluate()` method in the `crypto.py`.

2024-11-07 15:14 UTC, pkoprda commented on python/tests-unit/test_crypto.py
> +    shutil.rmtree(home)
I put the `shutil.rmtree(home)` before the asserts, like we already have in `test_valid_signature()` and `test_invalid_signature()`. I think it should be enough.

2024-11-07 15:14 UTC, pkoprda commented on python/tests-unit/test_crypto.py
> +    shutil.rmtree(home)
Same as above.

2024-11-07 15:31 UTC, m-horky requested changes

2024-11-12 08:54 UTC, pkoprda commented on python/tests-unit/test_crypto.py
> +        result: crypto.GPGCommandResult = gpg_command.evaluate()
Yes, that's true, mocking the process is the best idea :+1:

2024-11-12 08:56 UTC, m-horky approved these changes
LGTM

2024-11-12 09:22 UTC, merged